### ISSUE TITLE
Multiple Upload not working on mobile device (iphone)

### ISSUE THREAD

**Issue by stephangrass** [svewap/form_extended#13]
If the "multiple" attribute is specified with a value of "1", it will be interpreted as a simple "input" field, allowing only a single file to be uploaded.

In the template FileUpload.html it helps if the attribute multiple is filled with the following condition:

multiple="{f:if(condition: '{element.properties.enableMulitple}', then: 'multiple')}"

**Comment by BastianBalthasarBux** [comment]
Fixed, see #6

**Comment by stephangrass** [comment]
I think not really. The multiple attribute must be written either without a value or multiple="multiple".

`multiple="{f:if(condition: '{element.properties.enableMulitple}', then: 'multiple')}"`

**Comment by BastianBalthasarBux** [comment]
`multiple="{f:if(condition:element.properties.multiple,then:'multiple')}"`

**Comment by svewap** [comment]
Should be fixed with ccf70809f6b83085ad8bda62c306d03a5b7c79b0
