### ISSUE TITLE
Version for TYPO3 12

### ISSUE THREAD

**Issue by stephangrass** [svewap/form_extended#15]
Hi,
will there be a version for TYPO3 12 in the short term?

Thanks
Stephan

**Comment by svewap** [comment]
Currently there is no plan yet

**Comment by stephangrass** [comment]
That's a pity. Our primary focus is the multiple file upload, which we urgently require for a TYPO3-12 project.

**Comment by svewap** [comment]
You know the options: Do it yourself and possibly contribute, wait or sponsor. ;-)

**Comment by stephangrass** [comment]
Jau ;-)
How much would my sponsorship need to be in order to have a version available for TYPO3 12 by early August?

**Comment by svewap** [comment]
To be fair: I can't accurately estimate it at the moment. Maybe something between 1 and 4 hours maybe, for the multi upload field. 
A budget of 4 hours would of course increase the priority.
But if the function already works without my intervention, then only 1 hour.

**Comment by stephangrass** [comment]
I need to clarify this internally. 200 euros should be possible. Anything more would unfortunately upset the already tight budget.

**Comment by stephangrass** [comment]
Hi,
Could we expedite the update of the extension for TYPO3 12 with a sponsorship of about 200 Euros? We are primarily interested in the multi upload field.

**Comment by svewap** [comment]
Hi,
Thank you for sponsoring further development. Unfortunately, the amount does not allow an exact schedule, but it already looks quite good.
