### ISSUE TITLE
[BUG] in release/v12 "Argument 'accept' has already been defined, thus it should not be defined again."

### ISSUE THREAD

**Issue by bh-teufels** [svewap/form_extended#16]
at TYPO3Fluid\Fluid\Core\ViewHelper\AbstractViewHelper->registerArgument('accept', 'array', 'Values for the accept attribute', false, array())
in /app/vendor/wapplersystems/form_extended/Classes/ViewHelpers/Form/UploadedResourceViewHelper.php line 78

Argument "accept" is used twice

```
$this->registerTagAttribute('accept', 'string', 'Specifies the allowed file extensions to upload via comma-separated list, example ".png,.gif"');
[...]
$this->registerArgument('accept', 'array', 'Values for the accept attribute', false, []);
```

**Comment by icehawk-de** [comment]
Got the same problem.
This: https://github.com/WapplerSystems/form_extended/pull/19 in the Classes/ViewHelpers/Form/UploadedResourceViewHelper.php fixes the problem.
As mentioned above.

**Comment by svewap** [comment]
fixed
