### ISSUE TITLE
BUG: {element.properties.multiple} does not exist it is {element.properties.enableMulitple}

### ISSUE THREAD

**Issue by bh-teufels** [svewap/form_extended#6]
Inside FileUpload.html for the Input Field multiple is set by
`multiple="{element.properties.multiple}"`
but `{element.properties.multiple}` does not exist it is `{element.properties.enableMulitple}`

and enableMulitple = "FALSE" does not disable multiple Upload

Environment:
Typo3 11.5.22
PHP 8.1.2
form_extended 11.0.0

**Comment by rintisch** [comment]
@svewap This can be closed because it's fixed with 8ecb920 !?
