### ISSUE TITLE
BUG: Using form with steps and multiple file upload causes error "#1297759968 TYPO3\CMS\Extbase\Property\Exception"

### ISSUE THREAD

**Issue by bh-teufels** [svewap/form_extended#8]
#1297759968 TYPO3\CMS\Extbase\Property\Exception
Exception while property mapping at property path "": Property "0" was not found in target object of type "TYPO3\CMS\Extbase\Domain\Model\FileReference".

at TYPO3\CMS\Extbase\Property\PropertyMapper->convert(array(null, null), 'TYPO3\\CMS\\Extbase\\Domain\\Model\\FileReference')
in /app/web/typo3conf/ext/form_extended/Classes/ViewHelpers/UploadedResourcesViewHelper.php line 54

`return $this->propertyMapper->convert($resource, FileReference::class);`

when $resource is array because of  multiple file upload.

Environment:
Typo3 11.5.22
PHP 8.1.2
form_extend 11.0.0

**Comment by svewap** [comment]
This bug should be fixed now or maybe partly. I didn't checked all finishers.
