### ISSUE TITLE
Do not use jQuery

### ISSUE THREAD

**Issue by rintisch** [svewap/form_extended#9]
The JS for the multiple fileupload uses jQuery. Vanilla JS would be better and future proof. 
I will create a PR for this.

**Comment by svewap** [comment]
I committed an update with vanilla with 2554a0a2d2150dfed08209531bf7355883e401f3 . I changed other things too. Thanks four your PR as inspiration.

**Comment by rintisch** [comment]
This is solved so I will close this issue.
